# Generated by Django 2.1.1 on 2018-11-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20181111_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='mgr_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
