# Generated by Django 2.1.1 on 2018-11-19 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_hospital_mgr_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hosp_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
