# Generated by Django 2.1.1 on 2018-11-19 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_auto_20181119_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='hosp_id',
        ),
    ]
