# Generated by Django 2.1.1 on 2018-11-19 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_remove_hospital_hosp_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='name',
            new_name='hosp_name',
        ),
    ]
