# Generated by Django 2.1.1 on 2018-11-19 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_auto_20181119_0843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='hosp_name',
            new_name='name',
        ),
    ]
