# Generated by Django 2.1.1 on 2018-11-12 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Managers',
        ),
    ]
