# Generated by Django 2.1.1 on 2018-11-14 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0002_auto_20181113_0143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managers',
            old_name='age',
            new_name='mgr_age',
        ),
        migrations.RenameField(
            model_name='managers',
            old_name='city',
            new_name='mgr_city',
        ),
        migrations.RenameField(
            model_name='managers',
            old_name='district',
            new_name='mgr_district',
        ),
        migrations.RenameField(
            model_name='managers',
            old_name='email',
            new_name='mgr_email',
        ),
        migrations.RenameField(
            model_name='managers',
            old_name='gender',
            new_name='mgr_gender',
        ),
        migrations.RenameField(
            model_name='managers',
            old_name='name',
            new_name='mgr_name',
        ),
        migrations.RenameField(
            model_name='managers',
            old_name='password',
            new_name='mgr_password',
        ),
        migrations.RenameField(
            model_name='managers',
            old_name='phone',
            new_name='mgr_phone',
        ),
        migrations.RenameField(
            model_name='managers',
            old_name='place',
            new_name='mgr_place',
        ),
        migrations.RenameField(
            model_name='managers',
            old_name='username',
            new_name='mgr_username',
        ),
    ]
