# Generated by Django 2.1.1 on 2018-11-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancerdet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('symptom', models.CharField(default='', max_length=50)),
                ('cause', models.CharField(default='', max_length=50)),
                ('test', models.CharField(default='', max_length=50)),
                ('treatment', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
