# Generated by Django 2.1.1 on 2018-11-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancerdet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancerdet',
            name='mgr_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
