# Generated by Django 2.1.1 on 2018-10-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180928_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.BigIntegerField(),
        ),
    ]
