# Generated by Django 2.1.1 on 2018-10-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20181006_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='charitytype',
            field=models.CharField(default=(('Blood', 'Blood'), ('Hair', 'Hair')), max_length=30),
        ),
    ]
