# Generated by Django 2.1.1 on 2018-10-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20181007_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='charitytype',
            field=models.CharField(choices=[('Blood', 'Blood'), ('Hair', 'Hair')], max_length=30),
        ),
    ]
