# Generated by Django 2.1.1 on 2018-09-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityorg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charityorg',
            name='charitytype',
            field=models.CharField(default='', max_length=30),
        ),
    ]
