# Generated by Django 2.1.1 on 2018-11-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_auto_20181111_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='mgr_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctors',
            name='hosp_id',
            field=models.BigIntegerField(),
        ),
    ]
