# Generated by Django 2.1.1 on 2018-11-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_auto_20181119_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='hosp_id',
        ),
        migrations.AddField(
            model_name='doctors',
            name='hosp_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
