# Generated by Django 2.1.1 on 2018-10-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0002_auto_20180928_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='parlour',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='parlour',
            name='username',
            field=models.CharField(default='', max_length=30),
        ),
    ]
