# Generated by Django 2.1.1 on 2018-11-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0003_auto_20181021_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parlour',
            name='password',
        ),
        migrations.RemoveField(
            model_name='parlour',
            name='username',
        ),
        migrations.AddField(
            model_name='parlour',
            name='mgr_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
